### ISSUE TITLE
Bios recovery surftab-twin-10.1-ST10432-8

### ISSUE THREAD

**Issue by UUSR** [onitake/gsl-firmware#121]
Hello, I need help, my surftab-twin-10.1-ST10432-8 does not turn on. I tried to change the BIOS settings and after that it stopped turning on. How do I restore the BIOS settings.

**Comment by onitake** [comment]
I'm sorry but this is not a support forum for tablet computers.
Please keep your questions focused on Silead touchscreen controllers and corresponding firmware.
