### ISSUE TITLE
where is touchscreen_dmi.c - configure silead_ts

### ISSUE THREAD

**Issue by vinodkrishnanr** [onitake/gsl-firmware#153]
I'm trying to configure silead_ts and it is mentioned

> Fetch the current Linux source code and open drivers/platform/x86/silead_dmi.c in a text editor. Since Linux kernel 4.19, this file is called drivers/platform/x86/touchscreen_dmi.c.

I can't find this in my kernel 5.4.0-52 under x86 folder. 

Can someone please help?

**Comment by onitake** [comment]
Please do not post support questions that are not firmware related here.
Thank you.

You can find the file easily: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/platform/x86/touchscreen_dmi.c
There's even a mirror on Github that shows up as the first Google search result.
