### ISSUE TITLE
Jittery Touchscreen

### ISSUE THREAD

**Issue by 0x0000ff** [onitake/gsl-firmware#178]
Hello there,

I've managed to get the touchscreen working on my x86 tablet (Viglen Connect 10) with the silead_ts driver, but the touch screen is very jittery when dragging windows and scrolling, and I don't think it can properly register GUI button presses. I see there's some 'touchscreen-fuzz' attributes that are used in the touchscreen_dmi source code that i've used, but that doesn't seem to remedy it. 

Perhaps there's some option to filter it out with hwdb rules libinput? I'm not sure where to look to see if there is.

Thanks,
0x0000ff

**Comment by jwrdegoede** [comment]
On 10/3/21 5:59 PM, 0x0000ff wrote:
> I've managed to get the touchscreen working on my x86 tablet (Viglen Connect 10) with the silead_ts driver, but the touch screen is very jittery when dragging windows and scrolling, and I don't think it can properly register GUI button presses. I see there's some 'touchscreen-fuzz' attributes that are used in the touchscreen_dmi source code that i've used, but that doesn't seem to remedy it.
> 
> Perhaps there's some option to filter it out with hwdb rules libinput? I'm not sure where to look to see if there is.

Is this with a charger connected to the tablet ?

Some (cheap/brandless) chargers generate a lot of electrical noise ontop of the 5V they are supplying and Silead touchscreens are quite sensitive to this.

Try using the touchscreen without the charger connected, and if that helps, try using a different charge / buy another charger. I've good luck with using the Dell 5V/2A chargers from the Dell Venue 8 pro models. These chargers seem to supply a nice clean 5V.

**Comment by 0x0000ff** [comment]
It's not charging and it still persists. Does touchscreen-fuzz help with remedying this?

**Comment by jwrdegoede** [comment]
> It's not charging and it still persists. Does touchscreen-fuzz help with remedying this?

If this still happens when no charger is connected then touchscreen-fuzz might help a bit.

**Comment by 0x0000ff** [comment]
Ok. I have the coordinates for the fuzz set at 30. Is that maybe too high?

Thank you for working on the drivers btw.

**Comment by jwrdegoede** [comment]
On 10/3/21 6:23 PM, 0x0000ff wrote:
> Ok. I have the coordinates for the fuzz set at 30. Is that maybe too high?

30 indeed sounds quite high, 5 - 8 or something like that is probably best.

**Comment by 0x0000ff** [comment]
Ok. I used another firmware file and it seems to have sorted it. I've kept the fuzz because it still flickers a bit. I'll try to upload my progress so far with some pull requests. Thanks for your help.

**Comment by Lehmaning** [comment]
Could you tell me how did you fix it in more detail? I have no idea about setting the touchscreen-fuzz...
