### ISSUE TITLE
cube i10w

### ISSUE THREAD

**Issue by kahrloz** [onitake/gsl-firmware#20]
i got fw_extractor to work off my android-tablet's.ko, however i don't know how to make use of the fw files so that my touchscreen works.

**Comment by onitake** [comment]
I responded to your question in [gslx680-acpi#16](https://github.com/onitake/gslx680-acpi/issues/16), but feel free to continue the discussion here.

**Comment by onitake** [comment]
In response to https://github.com/onitake/gslx680-acpi/issues/16#issuecomment-230628395 :
Have you tried all the firmware files, and did you enable finger tracking?
What was your fwtool command line?

**Comment by onitake** [comment]
I downloaded the Windows driver you posted and converted it.
It's here: https://github.com/onitake/gsl-firmware/tree/master/firmware/cube/i10
The result is possibly not the same as yours.
Can you test that and report your results?

**Comment by kahrloz** [comment]
OK

**Comment by kahrloz** [comment]
It's works perfectly

**Comment by onitake** [comment]
Thanks!
