### ISSUE TITLE
Convert GSL_TS_CFG.h back to SileadTouch.fw to fix touch rotation on Microsoft Windows

### ISSUE THREAD

**Issue by bcm0** [onitake/gsl-firmware#209]
I guess Microsoft Windows confuses X and Y touch axis because of a missing `SileadTouch.fw`.

There is no such file in the repository of this Trekstor tablet https://github.com/onitake/gsl-firmware/tree/master/firmware/trekstor/surftab-twin-10.1-ST10432-8

Can I scramble [GSL_TS_CFG_THREE.h](https://github.com/onitake/gsl-firmware/blob/master/firmware/trekstor/surftab-twin-10.1-ST10432-8/Windows_System32_drivers/GSL_TS_CFG_THREE.h) into `SileadTouch.fw`?

I tried `tools/unscramble GSL_TS_CFG_THREE.h SileadTouch.fw` but the file created is empty.

Why does the extracted firmware work on linux without problems?

> If you have a Windows driver instead, the firmware either comes in the form of a file named GSL_TS_CFG.h (or similar) or SileadTouch.fw. The latter is just a scrambled version of GSL_TS_CFG.h and can be easily restored by XORing every byte with 0x88. https://github.com/onitake/gsl-firmware#windows-driver

> They just XOR everything with 0x88, then skim over the result (which is exactly the content of GSL_TS_CFG.h) until they find "GSL_TS_CFG", then convert the hex values that follow into binary, and that's the firmware image.
https://github.com/onitake/gsl-firmware/issues/3#issuecomment-179264645

**Comment by onitake** [comment]
`tools/unscramble` is used to **unscramble** SileadTouch.fw, not the the other way round.
But the algorithm is pretty trivial, so can just modify the script to run the XOR and skip the part that extracts the firmware blob.
