### ISSUE TITLE
Issue with silead_ts.fw on Kernel 4.10.0.10-linuxium

### ISSUE THREAD

**Issue by dan-mirescu** [onitake/gsl-firmware#33]
Hi,

I've been trying for some time to make my touchscreen work on Ubuntu.

My device is named AllView Wi901N (9 inches), it is a BayTrail tablet and comes preinstalled only with Windows 10. Unfortunately, there is very little technical information available.
The following are the SileadTouch.sys and SileadTouch.fw that come with the tablet:
[SileadTouch.zip](https://github.com/onitake/gsl-firmware/files/852743/SileadTouch.zip)

Lately I used the Ubuntu "16.04.2" build done by Linuxium which contains patches that make a lot of devices work on my tablet, which otherwise wouldn't with the mainstream Ubuntu.

I guess that the new kernel version (and the fact that it's been modified, also including the "silead" driver) prevent the gslx680-acpi driver from functioning properly.

I used both SileadTouch.fw (unscrambled then compacted it) and I also extracted the firmware from SileadTouch.sys, then compacted it.

Here are the silead_ts.fw files I obtained:
[silead_ts.zip](https://github.com/onitake/gsl-firmware/files/852755/silead_ts.zip)

Using the silead_ts.fw files obtained from both methods, I get the following:

>  404.713398] gslx680 i2c-MSSL1680:00: gsl_ts_probe: got a device named MSSL1680:00 at address 0x40, IRQ 194, flags 0x0
[  404.714002] input: Silead GSLx680 Touchscreen as /devices/platform/80860F41:03/i2c-11/i2c-MSSL1680:00/input/input10
[  404.919854] i2c_designware 80860F41:03: i2c_dw_handle_tx_abort: lost arbitration
[  404.920287] i2c_designware 80860F41:03: i2c_dw_handle_tx_abort: lost arbitration
[  404.920635] i2c_designware 80860F41:03: i2c_dw_handle_tx_abort: lost arbitration
[  404.923797] i2c_designware 80860F41:03: i2c_dw_handle_tx_abort: lost arbitration
[  404.923824] gslx680 i2c-MSSL1680:00: gsl_ts_reset_chip: gsl_ts_write 1 fail!
[  404.923839] gslx680 i2c-MSSL1680:00: gsl_ts_probe: chip reset failed
[  404.994041] gslx680: probe of i2c-MSSL1680:00 failed with error -11

After a reboot, those are the entries related to i2c (note that the silead driver is automatically loaded)
These messages appear regardless if there is a firmware file present or not.

>[    2.511229] i2c /dev entries driver
[    8.871782] i2c_designware 80860F41:04: I2C bus managed by PUNIT
[    8.958705] axp20x-i2c i2c-INT33F4:00: AXP20x variant AXP288 found
[    8.971020] i2c-MSSL1680:00 supply vddio not found, using dummy regulator
[    8.971049] i2c-MSSL1680:00 supply avdd not found, using dummy regulator
[    9.018663] axp20x-i2c i2c-INT33F4:00: AXP20X driver loaded
[    9.027616] silead_ts i2c-MSSL1680:00: Silead chip ID: 0x50910000
[    9.027920] i2c_designware 80860F41:03: i2c_dw_handle_tx_abort: lost arbitration
[    9.028331] i2c_designware 80860F41:03: i2c_dw_handle_tx_abort: lost arbitration
[    9.028724] i2c_designware 80860F41:03: i2c_dw_handle_tx_abort: lost arbitration
[    9.029116] i2c_designware 80860F41:03: i2c_dw_handle_tx_abort: lost arbitration
[    9.029238] silead_ts i2c-MSSL1680:00: Registers clear error -11
[    9.038946] silead_ts: probe of i2c-MSSL1680:00 failed with error -11
[    9.653009] input: axp20x-pek as /devices/platform/80860F41:04/i2c-12/i2c-INT33F4:00/axp20x-pek/input/input9

Later, after restarting silead (rmmod and modprobe), I get the following.
Again, those messages are generated regardless if there is a firmware file present or not.
>[ 1890.748093] i2c-MSSL1680:00 supply vddio not found, using dummy regulator
[ 1890.748170] i2c-MSSL1680:00 supply avdd not found, using dummy regulator
[ 1890.748422] silead_ts i2c-MSSL1680:00: Shutdown GPIO request failed
[ 1890.764675] silead_ts: probe of i2c-MSSL1680:00 failed with error -16

I also removed the silead driver during the tests with gslx680-acpi, with no success unfortunately.

**Comment by onitake** [comment]
These errors are caused by a conflict with ACPI management of the Silead chip's shutdown pin.
There is an ongoing discussion on linux-input on how to fix this issue, and I believe a solution has already been found.
Until a fix is available, please test with an older kernel. This should give you better results for the time being.
