### ISSUE TITLE
please add teclast x3 plus firmware

### ISSUE THREAD

**Issue by DoJungJin** [onitake/gsl-firmware#55]
I tested it working.

download firmware and silead_ts.fw files through below link.
http://download.djjproject.com/teclast_x3_plus/touch_firmware

device : 1680
width : 1980
height : 1500
options : track

I find touch panel size through experiment (about 120 times..)
that value is estimated value, but good working!

merge please. maybe this file can help others.

thank you.

**Comment by onitake** [comment]
@ponces just added the requested firmware in #58 .
I'm closing this issue.

**Comment by ponces** [comment]
This was only possible with the findings of @DoJungJin !

**Comment by onitake** [comment]
Thank you @DoJungJin too, of course!

If you want to help some more, please make the firmware work with the "official" kernel driver (silead.ko).
PR #56 should give you an idea on how to do this.
Thank you!

**Comment by ponces** [comment]
What should be that file? firmware.fw or silead_ts.fw?
What should be its name? "gsl1680-teclast-x3-plus.fw"?
Where should I change the silead_dmi.c?

Thank you!

**Comment by onitake** [comment]
`silead_ts.fw` is only for gslx680-acpi. `firmware.fw` should be the the "vanilla" firmware.
silead.ko needs a unique name so the files don't get mixed up.
Usually that includes the chip, manufacturer and device, so your suggestion (gsl1680-teclast-x3-plus.fw) is perfectly fine.

As soon as you have made and tested the modifications, please post them here for a short review.
Then send them to the linux-input mailing list: http://vger.kernel.org/vger-lists.html#linux-input

**Comment by onitake** [comment]
Sorry, I misread your question: silead_dmi.c is in `drivers/platform/x86/silead_dmi.c` of the Linux kernel sources. You need to recompile the silead.ko kernel module to test your changes.

**Comment by ponces** [comment]
It's working!
I could only make it to work using a combination of these three lines:
DMI_MATCH(DMI_SYS_VENDOR, "TECLAST"),
DMI_MATCH(DMI_PRODUCT_NAME, "X3 Plus"),
DMI_MATCH(DMI_BOARD_NAME, "X3 Plus")

Thank you for your help!

**Comment by onitake** [comment]
Thanks @DoJungJin and @ponces - I merged all of your work.

**Comment by onitake** [comment]
@ponces Did you submit your kernel patch to [linux-input](http://vger.kernel.org/vger-lists.html#linux-input)?
If not, please do. Thank you!

**Comment by ponces** [comment]
Yes, just now - https://patchwork.kernel.org/patch/10179961/

Thank you for your help!
