### ISSUE TITLE
Teclast X98 Plus II

### ISSUE THREAD

**Issue by pcercuei** [onitake/gsl-firmware#82]
The converted, Linux-ready firmware file can be found here:
https://wiki.archlinux.org/index.php/Teclast_X98_Plus_II#Touchscreen_.28works.29

I couldn't get a hand on the actual firmware files from the installed Windows or Android OSes, I flashed Linux as soon as I got mine...

**Comment by onitake** [comment]
Can you turn this into a pull request, please?
Thanks!
