### ISSUE TITLE
Ubuntu 18.10 calibration.

### ISSUE THREAD

**Issue by sheldonmaschmeyer** [onitake/gsl-firmware#95]
Hi, 
The driver and firmware is working in that the screen responds to my finger
The touchscreen is not calibrating. 
I tried xinput --map-to-output silead_ts DSI-1
when using xcal, all the points tend to group on the left (towards bottom) side of the screen. The tablet is docked to keyboard in landscape mode (rotated right). I also tried it in all screen orientations.
The matrix that xcal produces is roughly
[[0 -2 2]
[-3 0 1]
[0 0 1]]
The model is CWI529, HQ64G42161206XXX
I used the hi10_pro-z8350 firmware
Please advise.

Update: While xinput_calibrator does not work with newer versions of Ubuntu, it can output settings suggestions. It shows SwapXY "1" so, I need to swap the XY axis somehow. 
Section "InputClass"
	Identifier	"calibration"
	MatchProduct	"silead_ts"
	Option	"MinX"	"30808"
	Option	"MaxX"	"30648"
	Option	"MinY"	"16061"
	Option	"MaxY"	"16243"
	Option	"SwapXY"	"1" # unless it was already set to 1
	Option	"InvertX"	"0"  # unless it was already set
	Option	"InvertY"	"0"  # unless it was already set
EndSection

**Comment by onitake** [comment]
Ok, first: Why does xinput_calibrator no longer work? Did Ubuntu switch to Wayland?

**Comment by sheldonmaschmeyer** [comment]
It has both Wayland and Xorg regardless of which is chosen on login, Ubuntu uses libinput for the touchscreen. I do not believe there is any official calibration program for generic libinput touchscreens yet. I could edit the 40-libinput.conf file to remove the section with "libinput touchscreen catchall". Maybe it would make xinput_calibrator work?

**Comment by sheldonmaschmeyer** [comment]
Solved the problem, thanks to this little script https://github.com/danielotero/linux-on-hi10/blob/master/touchscreen/rotation (just modified DSI1 to DSI-1).
It isn't perfect but, it is a lot better. Eventually someone will make a touchscreen calibrator for modern Linux that actually works, xcal is mostly garbage. 
#!/bin/bash

set -e

TOUCHSCREEN='silead_ts'
XDISPLAY='DSI-1'
TRANSFORM='libinput Calibration Matrix'

X_SCALE=2.17
Y_SCALE=3.22
X_OFFSET=-0.045
Y_OFFSET=-0.004

if [ -z "$1" ]; then
  ROTATION=right
else
  ROTATION=$1
fi

xrandr --output $XDISPLAY --rotate $ROTATION
xinput set-prop 'silead_ts' --type=float "$TRANSFORM" 0 $Y_SCALE $Y_OFFSET $X_SCALE 0 $X_OFFSET 0 0 1
xinput --map-to-output "$TOUCHSCREEN" "$XDISPLAY"

**Comment by onitake** [comment]
Terrible stuff, but great that you got it working.

Though, in this case, it might be possible to solve calibration via DMI-based parameters. silead.ko, like most modern Linux HID drivers, supports this: https://github.com/torvalds/linux/blob/master/Documentation/devicetree/bindings/input/touchscreen/touchscreen.txt
